version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana.db:/etc/grafana/grafana.db
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/usr/share/grafana/conf/provisioning
      - ./grafana/provisioning:/etc/grafana/provisioning
  microservice-demo:
    image: microservice-demo
    ports:
      - 8000:8000
    build:
      context: microservice-demo/
      dockerfile: Dockerfile

volumes:
  prometheus-data:
